#!/usr/bin/env python3

lines = []
with open('8D28.pdb','r') as file:
    for i in range(500):
        lines.append(file.readline())


for line in lines:
    if line[:4] == 'ATOM':
        print(line)

